-- ============================================================
-- AutoTallerManager - Migración Inicial (TallerInit)
-- Generado: 2026-06-02
-- ============================================================

-- Tabla de historia de migraciones EF Core
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

-- ============================================================
-- TABLAS INDEPENDIENTES (sin FK)
-- ============================================================

CREATE TABLE "Clientes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NombreCompleto" character varying(150) NOT NULL,
    "Cedula" character varying(20) NOT NULL,
    "Telefono" character varying(20) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "PasswordHash" text NOT NULL,
    "EstadoCuenta" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Clientes" PRIMARY KEY ("Id")
);

CREATE TABLE "Repuestos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Codigo" character varying(50) NOT NULL,
    "Nombre" character varying(150) NOT NULL,
    "Descripcion" character varying(500),
    "Categoria" text NOT NULL,
    "CantidadStock" integer NOT NULL,
    "StockMinimo" integer NOT NULL,
    "PrecioCompra" numeric(18,2) NOT NULL,
    "PrecioVenta" numeric(18,2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Repuestos" PRIMARY KEY ("Id")
);

CREATE TABLE "rols" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "rolName" varchar(50) NOT NULL,
    "Description" character varying(50) NOT NULL,
    "createdAt" date NOT NULL DEFAULT CURRENT_DATE,
    "updatedAt" date NOT NULL DEFAULT CURRENT_DATE,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_rols" PRIMARY KEY ("id")
);

CREATE TABLE "users_members" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "name" character varying(50) NOT NULL,
    "email" character varying(50) NOT NULL,
    "Password" varchar(255) NOT NULL,
    "Estado" integer NOT NULL DEFAULT 0,
    "createdAt" date NOT NULL DEFAULT CURRENT_DATE,
    "updatedAt" date NOT NULL DEFAULT CURRENT_DATE,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_users_members" PRIMARY KEY ("id")
);

-- ============================================================
-- TABLAS CON FK A TABLAS INDEPENDIENTES
-- ============================================================

CREATE TABLE "Vehiculos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Marca" character varying(50) NOT NULL,
    "Modelo" character varying(50) NOT NULL,
    "Anio" integer NOT NULL,
    "Vin" character varying(17) NOT NULL,
    "Kilometraje" integer NOT NULL,
    "Placa" character varying(10) NOT NULL,
    "Color" character varying(30) NOT NULL,
    "ClienteId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Vehiculos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Vehiculos_Clientes_ClienteId" FOREIGN KEY ("ClienteId")
        REFERENCES "Clientes" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Auditorias" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EntidadAfectada" character varying(100) NOT NULL,
    "AccionRealizada" character varying(200) NOT NULL,
    "UsuarioId" integer,
    "Fecha" timestamp with time zone NOT NULL,
    "ValoresAnteriores" text,
    "ValoresNuevos" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Auditorias" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Auditorias_users_members_UsuarioId" FOREIGN KEY ("UsuarioId")
        REFERENCES "users_members" ("id") ON DELETE SET NULL
);

CREATE TABLE "refresh_tokens" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "user_id" integer NOT NULL,
    "token" character varying(256) NOT NULL,
    "expires" timestamp with time zone NOT NULL,
    "created" timestamp with time zone NOT NULL,
    "revoked" timestamp with time zone,
    "created_at" timestamp with time zone NOT NULL DEFAULT NOW(),
    "updated_at" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_refresh_tokens" PRIMARY KEY ("id"),
    CONSTRAINT "FK_refresh_tokens_users_members_user_id" FOREIGN KEY ("user_id")
        REFERENCES "users_members" ("id") ON DELETE CASCADE
);

CREATE TABLE "users_rols" (
    "UserMemberId" integer NOT NULL,
    "RolId" integer NOT NULL,
    CONSTRAINT "PK_users_rols" PRIMARY KEY ("UserMemberId", "RolId"),
    CONSTRAINT "FK_users_rols_rols_RolId" FOREIGN KEY ("RolId")
        REFERENCES "rols" ("id") ON DELETE CASCADE,
    CONSTRAINT "FK_users_rols_users_members_UserMemberId" FOREIGN KEY ("UserMemberId")
        REFERENCES "users_members" ("id") ON DELETE CASCADE
);

CREATE TABLE "OrdenesServicio" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NumeroOrden" character varying(50) NOT NULL,
    "VehiculoId" integer NOT NULL,
    "ClienteId" integer NOT NULL,
    "Estado" text NOT NULL,
    "FechaIngreso" timestamp with time zone NOT NULL,
    "FechaEstimadaEntrega" timestamp with time zone,
    "MecanicoId" integer,
    "Diagnostico" character varying(2000),
    "PropuestaReparacion" character varying(2000),
    "Observaciones" character varying(1000),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_OrdenesServicio" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrdenesServicio_Clientes_ClienteId" FOREIGN KEY ("ClienteId")
        REFERENCES "Clientes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_OrdenesServicio_Vehiculos_VehiculoId" FOREIGN KEY ("VehiculoId")
        REFERENCES "Vehiculos" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_OrdenesServicio_users_members_MecanicoId" FOREIGN KEY ("MecanicoId")
        REFERENCES "users_members" ("id") ON DELETE SET NULL
);

CREATE TABLE "DetallesOrden" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrdenServicioId" integer NOT NULL,
    "RepuestoId" integer NOT NULL,
    "CantidadUtilizada" integer NOT NULL,
    "PrecioUnitario" numeric(18,2) NOT NULL,
    "Subtotal" numeric(18,2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_DetallesOrden" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DetallesOrden_OrdenesServicio_OrdenServicioId" FOREIGN KEY ("OrdenServicioId")
        REFERENCES "OrdenesServicio" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_DetallesOrden_Repuestos_RepuestoId" FOREIGN KEY ("RepuestoId")
        REFERENCES "Repuestos" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Facturas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NumeroFactura" character varying(50) NOT NULL,
    "OrdenServicioId" integer NOT NULL,
    "ManoObra" numeric(18,2) NOT NULL,
    "TotalRepuestos" numeric(18,2) NOT NULL,
    "Impuestos" numeric(18,2) NOT NULL,
    "TotalFinal" numeric(18,2) NOT NULL,
    "EstadoPago" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Facturas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Facturas_OrdenesServicio_OrdenServicioId" FOREIGN KEY ("OrdenServicioId")
        REFERENCES "OrdenesServicio" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Pagos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FacturaId" integer NOT NULL,
    "MetodoPago" text NOT NULL,
    "FechaPago" timestamp with time zone NOT NULL,
    "Monto" numeric(18,2) NOT NULL,
    "ReferenciaTransaccion" character varying(100),
    "Estado" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Pagos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Pagos_Facturas_FacturaId" FOREIGN KEY ("FacturaId")
        REFERENCES "Facturas" ("Id") ON DELETE RESTRICT
);

-- ============================================================
-- ÍNDICES
-- ============================================================

CREATE INDEX "IX_Auditorias_UsuarioId" ON "Auditorias" ("UsuarioId");
CREATE UNIQUE INDEX "IX_Clientes_Cedula" ON "Clientes" ("Cedula");
CREATE INDEX "IX_DetallesOrden_OrdenServicioId" ON "DetallesOrden" ("OrdenServicioId");
CREATE INDEX "IX_DetallesOrden_RepuestoId" ON "DetallesOrden" ("RepuestoId");
CREATE UNIQUE INDEX "IX_Facturas_NumeroFactura" ON "Facturas" ("NumeroFactura");
CREATE UNIQUE INDEX "IX_Facturas_OrdenServicioId" ON "Facturas" ("OrdenServicioId");
CREATE INDEX "IX_OrdenesServicio_ClienteId" ON "OrdenesServicio" ("ClienteId");
CREATE INDEX "IX_OrdenesServicio_MecanicoId" ON "OrdenesServicio" ("MecanicoId");
CREATE UNIQUE INDEX "IX_OrdenesServicio_NumeroOrden" ON "OrdenesServicio" ("NumeroOrden");
CREATE INDEX "IX_OrdenesServicio_VehiculoId" ON "OrdenesServicio" ("VehiculoId");
CREATE INDEX "IX_Pagos_FacturaId" ON "Pagos" ("FacturaId");
CREATE UNIQUE INDEX "IX_refresh_tokens_token" ON "refresh_tokens" ("token");
CREATE INDEX "IX_refresh_tokens_user_id" ON "refresh_tokens" ("user_id");
CREATE UNIQUE INDEX "IX_Repuestos_Codigo" ON "Repuestos" ("Codigo");
CREATE UNIQUE INDEX "IX_users_members_email" ON "users_members" ("email");
CREATE INDEX "IX_users_rols_RolId" ON "users_rols" ("RolId");
CREATE INDEX "IX_Vehiculos_ClienteId" ON "Vehiculos" ("ClienteId");
CREATE UNIQUE INDEX "IX_Vehiculos_Placa" ON "Vehiculos" ("Placa");
CREATE UNIQUE INDEX "IX_Vehiculos_Vin" ON "Vehiculos" ("Vin");

-- ============================================================
-- REGISTRAR MIGRACIÓN EN HISTORIAL EF CORE
-- ============================================================
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260602133429_TallerInit', '9.0.5');
